# 에러처리
- 프로그램의 오류 조건에 응답하고 오류 조건에서 복구하는 프로세스입니다
- Swift는 런타임시 복구 가능한 오류를 던지고, 포착하고, 전파하고, 조작하는 기능을 제공합니다.- 에러는 Error 프로토콜을 준수하는 유형의 값으로 나타냅니다. 실제로 Error프로토콜은 비어 있으나 오류를 처리할수 있는 타입임을 나타냅니다. **(비어있는데 왜 채택하나? 타입을 맞추기위한 프로토콜로만든것, 우리가만드는 이넘이 에러라는문법을 통해서 배출이되려면 에러라는 프로토콜을 채택해야한다. 그래야 에러라는 타입으로 표출되고, 리턴값이 에러로 나올 수 있다.)**

- enum을 통해서 에러를 만들 수 있다.
- 함수안에 throws가 있으면 함수이름 뒤에 throws를 넣어준다.(잘못됐을때 에러를 던져주는 함수다 라는 뜻)->내부에서는 에러가있을때 마다 해당되는 에러의 열거형을 반환해준다.

- **에러처리**: 에러를 처리해야하는 메소드인지 아닌지 구분해야한다. 발견된 에러를 처리하기위해 do-catch문을 쓴다. do 부분에서 결과값을 반환 catch부분에서 에러가났을때의 코드가 실행된다. try를 붙여서 try -> 메소드 -> 에러가난다면 -> catch문으로 이동, do-catch문도 switch문 처럼 catch를 하나 더 써서 디폴트값을 넣어주면 모든에러를잡는다.(혹시 내가 발견하지못한 에러)

#### Converting Errors to Optional Value
- 에러가 나온다면 옵셔널로 처리해버린다

```swift
func someThrowingFunction() throws -> Int {// ...        }        let x = try? someThrowingFunction()

//여기서 에러가 나온다면 x에 옵셔널이 들어간다        
//위 아래 둘이 똑같은 코드
        let y: Int?        do {            y = try someThrowingFunction()} catch {y = nil }
```

#### Specifying Cleanup Actions (후처리)
- 에러가 발생했을때 문제가 생겨도 꼭 해야되는 행동을 처리한다.
- defer 구문은 블럭이 어떻게되던 꼭 실행된다.에러가 있어도 defer는 실행한다
- 에러가 발생이 안되도 함수가 끝나면 무조건 실행된다.
- defer가 있으면 역순으로 실행(코드를 다 읽고 에러가 있으면 맨아래 defer부터 실행)





